### ISSUE TITLE
Should `testModeAllowed` have a default value?

### ISSUE THREAD

**Issue by williamchong007** [luniehq/cosmos-ledger#6]
Currently when I directly use `Ledger()`  i.e.
```
const ledger = await Ledger().connect()
```
as instructed in readme, I will get the following error about `testModeAllowed`.

```Property 'testModeAllowed' is missing in type '{}' but required in type '{ testModeAllowed: Boolean; }```

Should the config object and `testModeAllowed` flag be optional instead for simpler syntax?

**Comment by faboweb** [comment]
Hey William, yes I agree that the config object should be optional. Would you be open to create a PR for that?
